FROM nginx:latest

COPY ./quickstart /usr/share/nginx/html/quickstart

RUN apt-get update && apt-get install -y git nano python3

RUN git clone https://github.com/sid-brest/sertis.by.git /usr/share/nginx/html/sertis

COPY replecerow.py /usr/share/nginx/html/sertis

RUN python3 /usr/share/nginx/html/sertis/replecerow.py